### ISSUE TITLE
More Python metadata

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#100]
Nirum currently generates Python packages with minimum required metadata such as `author`, `version`, and `name`.  [There are more][1] [than these fields][2]:

- [x] `description` (implemented by #174)
- [x] `license` (implemented by #180)
- [x] `keywords`
- [x] [`classifiers`][3] (implemented by #134?)

[1]: https://python-packaging.readthedocs.io/en/latest/metadata.html
[2]: https://docs.python.org/3/distutils/setupscript.html#additional-meta-data
[3]: http://pypi.python.org/pypi?%3Aaction=list_classifiers

**Comment by admire93** [comment]
I think it was finished on https://github.com/earlbread/nirum/commit/c348adeb4c443ed51f4902e2911140b6dafa873b. So I decided to close this issue.
