### ISSUE TITLE
Basic remote procedure call

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#25]
Primary remote procedure call has to be implemented:

```
// syntax has to be discussed more

boxed token (uuid);
union key = phone       (text phone_number)
          | qr-code     (text url)
          | credit-card (blob hash)
          ;
service customer (
    "GET /tokens/<token>/key/"
    key get-key-by-token (token token),
    "GET /tokens/groups/"
    {{token}} group-tokens ({token} tokens),
);
```

``` java
// client
class CustomerServiceClient {
    Future<Key> getKeyByToken(Future<Token> token);
    Future<Key> getKeyByToken(Token token);
    Future<Set<Set<Token>>> groupTokens(Future<Set<Token>> tokens);
    Future<Set<Set<Token>>> groupTokens(Set<Token> tokens);
}
CustomerService client = new CustomerServiceClient("https://customer.internal.spoqa.com/");
Key key = client.getKeyByToken(token);
```

``` java
// server
interface CustomerService {
    Key getKeyByToken(Token token);
    Set<Set<Token>> groupTokens(Set<Token> tokens);
}
class CustomerServiceImpl implements CustomerService {
    CustomerServiceImpl(Callable<Session> createSession) {
        this.session = session;
    }
    Key getKeyByToken(Token token) {
        // sql logic..
    }
    Set<Set<Token>> groupTokens(Set<Token> tokens) {
        // sql logic..
    }
}
new nirum.rpc.HttpServer<CustomerService>(
    new CustomerServiceImpl(getCurrentSession)
);
```

``` python
from nirum.rpc import WsgiApp
from werkzeug.wsgi import DispatcherMiddleware
from waitress import serve
app = DispatcherMiddleware({
    '/customer': WsgiApp(CustomerServiceImpl(get_session)),
    '/store': ...
})
serve(app, '', 8080)
```

Prerequisites:
- [x] #34 Annotation syntax is needed to specify manual url routing
- [x] New `service` keyword is necessary
- [x] Make Python target to generate service classes
- [x] spoqa/nirum-python#9 WSGI adaptor to serve RPC services on Python runtime
- [x] Client for RPC services spoqa/nirum-python#13

**Comment by dahlia** [comment]
Basic RPC was implemented except of manual URL routing.  Close this, and open a separated issue #130.
